# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citrix_answers', '0004_auto_20170708_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='citrix_answers.Tag'),
        ),
    ]
