# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citrix_answers', '0005_auto_20170711_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_solution',
            field=models.IntegerField(default=0),
        ),
    ]
